spring:
  r2dbc:
    url: r2dbc:pool:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:piggymetrics}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:secret}

  jmx:
    enabled: false

  sql:
    init:
      mode: never

  jooq:
    schema: ${DATABASE_SCHEMA:notification_service}
    sql-dialect: postgres

  liquibase:
    default-schema: ${DATABASE_SCHEMA:notification_service}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:piggymetrics}
    user: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:secret}

  cloud:
    kubernetes:
      reload:
        enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      subscribeTopics: ${USER_EVENTS_TOPIC:user-events}
      group-id: notification-service

  mail:
    host: smtp.gmail.com
    port: 465
    username: dev-user
    password: dev-password
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true

grpc:
  server:
    port: 9090

  client:
    account-service:
      address: "dns:///${ACCOUNT_SERVICE_HOST:localhost}:${ACCOUNT_SERVER_PORT:9090}"
      negotiationType: PLAINTEXT