spring:
  r2dbc:
    url: r2dbc:pool:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:piggymetrics}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:secret}

  jmx:
    enabled: false

  sql:
    init:
      mode: never

  jooq:
    schema: ${DATABASE_SCHEMA:notification_service}
    sql-dialect: postgres

  liquibase:
    default-schema: ${DATABASE_SCHEMA:notification_service}

  cloud:
    kubernetes:
      reload:
        enabled: true

    function:
      definition: userRegisteredEventConsumer

    stream:
      bindings:
        userRegisteredEventConsumer-in-0:
          destination: ${USER_EVENTS_TOPIC:user-events}
          content-type: application/x-protobuf

      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}

  mail:
    host: smtp.gmail.com
    port: 465
    username: dev-user
    password: dev-password
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true

grpc:
  server:
    port: 9090

  client:
    account-service:
      address: "dns:///${ACCOUNT_SERVICE_HOST:localhost}:${ACCOUNT_SERVER_PORT:9090}"
      negotiationType: PLAINTEXT