apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: piggymetrics/frontend
      context: ./pgm-frontend
    - image: piggymetrics/api-gateway
      jib:
        project: api-gateway
    - image: piggymetrics/account-service
      jib:
        project: account-service
    - image: piggymetrics/notification-service
      jib:
        project: notification-service
    - image: piggymetrics/statistics-service
      jib:
        project: statistics-service
deploy:
  helm:
    releases:
      - name: pgm-dev
        chartPath: ./charts/piggymetrics
        artifactOverrides:
          pgm-frontend.image: piggymetrics/frontend
          api-gateway.image: piggymetrics/api-gateway
          account-service.image: piggymetrics/account-service
          notification-service.image: piggymetrics/notification-service
          statistics-service.image: piggymetrics/statistics-service
        imageStrategy:
          helm: {}
        setValues:
          pgm-frontend.enabled: false
          api-gateway.enabled: false
          account-service.enabled: false
          notification-service.enabled: false
          statistics-service.enabled: true
        valuesFiles:
          - ./charts/global-values.yaml
