apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgm-frontend
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.global.pgm.frontend.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
