apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "statistics-service.configmap" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{- (.Files.Glob "files/application.yml").AsConfig | nindent 2 }}