{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: [{{ include "statistics-service.configmap" . | quote }}]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    resourceNames: [{{ include "common.names.fullname" . | quote }}]
    verbs: ["get"]
{{- end -}}