{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "statistics-service.serviceAccount" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
{{- end }}