apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "piggymetrics.vsvcCM" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{- tpl (.Files.Glob "files/istio-vsvc.yaml").AsConfig . | nindent 2 }}