apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "piggymetrics.hook.name" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "piggymetrics.hook.name" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
rules:
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices"]
    verbs: ["get", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "piggymetrics.hook.name" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ include "piggymetrics.hook.name" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "piggymetrics.hook.name" . }}