apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-create-vsvc-job
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "piggymetrics.hook.name" . }}
      containers:
        - name: create-vsvc-job
          image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
          imagePullPolicy: {{ .Values.kubectl.image.pullPolicy }}
          command:
            - sh
            - -c
            - eval "echo \"$(cat /etc/pgm/istio-vsvc.yaml)\"" | kubectl apply -f -
          env:
            - name: KEYCLOAK_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.keycloak.configMap }}
                  key: keycloak-host
            - name: KEYCLOAK_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.keycloak.configMap }}
                  key: keycloak-port
          volumeMounts:
            - name: istio-vsvc-config
              mountPath: /etc/pgm
      restartPolicy: Never
      volumes:
        - name: istio-vsvc-config
          configMap:
            name: {{ include "piggymetrics.vsvcCM" . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-delete-vsvc-job
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "piggymetrics.hook.name" . }}
      containers:
        - name: delete-vsvc-job
          image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
          imagePullPolicy: {{ .Values.kubectl.image.pullPolicy }}
          command:
            - sh
            - -c
            - kubectl delete virtualservices {{ include "common.names.fullname" . }}
      restartPolicy: Never