{{- if .Values.keycloakx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.keycloak.configMap }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  keycloak-host: {{ include "pgm-dependencies.keycloak.host" . }}
  keycloak-port: {{ .Values.keycloakx.service.httpPort | quote }}
{{- end }}