{{- if .Values.keycloakx.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-admin-creds
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}