{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-initdb-scripts
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{- with .Files.Glob "files/*.sh" }}
  {{- tpl (.AsConfig) $ | nindent 2 }}
  {{- end }}
{{- end }}