{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.postgresql.secret }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  pgm-postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  keycloak-postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}