global:
  postgresql:
    configMap: pgm-postgres-host
    secret: pgm-postgres-secret
    service:
      ports:
        postgresql: 5432

  kafka:
    servicePort: 9092
    configMap: pgm-kafka-brokers

    topic:
      userEvents: user-events
      accountEvents: account-events

  keycloak:
    configMap: pgm-keycloak-host
    provider:
      image:
        repository: galleog/piggymetrics-keycloak-provider
        tag: latest
        pullPolicy: Always

  pgm:
    database:
      name: pgm
      user: pgm

    frontend:
      port: 80

    gateway:
      port: 8080

    accountService:
      port: 9090
      database:
        schema: account_service

    notificationService:
      port: 9090
      database:
        schema: notification_service

    statisticsService:
      port: 9090
      database:
        schema: statistics_service