apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: {{ include "account-service.serviceAccount" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_TOOL_OPTIONS
            {{- if .Values.debug.enabled }}
              value: "-XX:+PrintFlagsFinal -XX:MaxRAMPercentage=50.0 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address={{ default 5005 .Values.debug.port }}"
            {{- else }}
              value: "-XX:+PrintFlagsFinal -XX:MaxRAMPercentage=50.0"
            {{- end }}
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.postgresql.configMap }}
                  key: postgres-host
            - name: DATABASE_PORT
              value: {{ .Values.global.postgresql.service.ports.postgresql | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.global.pgm.database.name }}
            - name: DATABASE_USER
              value: {{ .Values.global.pgm.database.user }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.postgresql.secret }}
                  key: pgm-postgres-password
            - name: DATABASE_SCHEMA
              value: {{ .Values.global.pgm.accountService.database.schema }}
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.kafka.configMap }}
                  key: kafka-brokers
            - name: USER_EVENTS_TOPIC
              value: {{ .Values.global.kafka.topic.userEvents }}
            - name: ACCOUNT_EVENTS_TOPIC
              value: {{ .Values.global.kafka.topic.accountEvents }}
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
              value: {{ include "account-service.configmap" . }}
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
              value: {{ .Release.Namespace }}
          ports:
            - name: grpc
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            grpc:
              port: 9090
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 10 .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ default 1 .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ default 3 .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            grpc:
              port: 9090
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 10 .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ default 1 .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ default 3 .Values.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
