spring:
  r2dbc:
    url: r2dbc:pool:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:piggymetrics}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:secret}

  jmx:
    enabled: false

  jooq:
    schema: ${DATABASE_SCHEMA:statistics_service}
    sql-dialect: postgres

  liquibase:
    default-schema: ${DATABASE_SCHEMA:statistics_service}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:piggymetrics}
    user: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:secret}

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      subscribeTopics: ${ACCOUNT_EVENT_TOPIC:account-events}
      group-id: statistics-service

grpc:
  server:
    port: 9090