spring:
  r2dbc:
    url: r2dbc:pool:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:piggymetrics}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:secret}

  jmx:
    enabled: false

  jooq:
    schema: ${DATABASE_SCHEMA:statistics_service}
    sql-dialect: postgres

  liquibase:
    default-schema: ${DATABASE_SCHEMA:statistics_service}

  cloud:
    function:
      definition: accountUpdatedEventConsumer

    stream:
      bindings:
        aaccountUpdatedEventConsumer-in-0:
          destination: ${ACCOUNT_EVENT_TOPIC:account-events}
          content-type: application/x-protobuf

      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}

grpc:
  server:
    port: 9090