apiVersion: v2
appVersion: "1.0"
name: pgm-dependencies
version: 0.1.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.0.1
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.8.1
    condition: postgresql.enabled
  - name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: 18.3.0
    condition: kafka.enabled
  - name: keycloakx
    repository: https://codecentric.github.io/helm-charts
    version: 1.6.0
    condition: keycloakx.enabled
