apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notification-service
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.global.pgm.notificationService.port }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
